# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(822, 953)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(7, 70, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupbox_io = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox_io.setGeometry(QtCore.QRect(10, 80, 611, 161))
        self.groupbox_io.setTitle("")
        self.groupbox_io.setObjectName("groupbox_io")
        self.label = QtWidgets.QLabel(self.groupbox_io)
        self.label.setGeometry(QtCore.QRect(10, 30, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtInputPath = QtWidgets.QTextBrowser(self.groupbox_io)
        self.txtInputPath.setGeometry(QtCore.QRect(240, 30, 251, 31))
        self.txtInputPath.setAcceptRichText(False)
        self.txtInputPath.setObjectName("txtInputPath")
        self.btnBrowseInput = QtWidgets.QPushButton(self.groupbox_io)
        self.btnBrowseInput.setEnabled(True)
        self.btnBrowseInput.setGeometry(QtCore.QRect(500, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Haas Grot Text R Web,Helvetica Neue,Helvetica,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.btnBrowseInput.setFont(font)
        self.btnBrowseInput.setStyleSheet("background-color: #EA4C89;\n"
"border-radius: 8px;\n"
"border-style: none;\n"
"box-sizing: border-box;\n"
"color: #FFFFFF;\n"
"cursor: pointer;\n"
"display: inline-block;\n"
"font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"height: 40px;\n"
"line-height: 20px;\n"
"list-style: none;\n"
"margin: 0;\n"
"outline: none;\n"
"padding: 10px 16px;\n"
"position: relative;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"transition: color 100ms;\n"
"vertical-align: baseline;\n"
"user-select: none;\n"
"-webkit-user-select: none;\n"
"touch-action: manipulation;")
        self.btnBrowseInput.setCheckable(False)
        self.btnBrowseInput.setObjectName("btnBrowseInput")
        self.label_3 = QtWidgets.QLabel(self.groupbox_io)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtOutputPath = QtWidgets.QTextBrowser(self.groupbox_io)
        self.txtOutputPath.setGeometry(QtCore.QRect(240, 70, 251, 31))
        self.txtOutputPath.setObjectName("txtOutputPath")
        self.btnBrowseOutput = QtWidgets.QPushButton(self.groupbox_io)
        self.btnBrowseOutput.setGeometry(QtCore.QRect(500, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Haas Grot Text R Web,Helvetica Neue,Helvetica,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.btnBrowseOutput.setFont(font)
        self.btnBrowseOutput.setStyleSheet("background-color: #EA4C89;\n"
"border-radius: 8px;\n"
"border-style: none;\n"
"box-sizing: border-box;\n"
"color: #FFFFFF;\n"
"cursor: pointer;\n"
"display: inline-block;\n"
"font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"height: 40px;\n"
"line-height: 20px;\n"
"list-style: none;\n"
"margin: 0;\n"
"outline: none;\n"
"padding: 10px 16px;\n"
"position: relative;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"transition: color 100ms;\n"
"vertical-align: baseline;\n"
"user-select: none;\n"
"-webkit-user-select: none;\n"
"touch-action: manipulation;")
        self.btnBrowseOutput.setObjectName("btnBrowseOutput")
        self.checkbox_file = QtWidgets.QCheckBox(self.groupbox_io)
        self.checkbox_file.setGeometry(QtCore.QRect(10, 120, 101, 20))
        self.checkbox_file.setChecked(True)
        self.checkbox_file.setObjectName("checkbox_file")
        self.checkbox_folder = QtWidgets.QCheckBox(self.groupbox_io)
        self.checkbox_folder.setGeometry(QtCore.QRect(130, 120, 111, 20))
        self.checkbox_folder.setCheckable(True)
        self.checkbox_folder.setChecked(False)
        self.checkbox_folder.setObjectName("checkbox_folder")
        self.btnRun = QtWidgets.QPushButton(self.groupbox_io)
        self.btnRun.setEnabled(True)
        self.btnRun.setGeometry(QtCore.QRect(240, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Haas Grot Text R Web,Helvetica Neue,Helvetica,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.btnRun.setFont(font)
        self.btnRun.setStyleSheet("background-color: #EA4C89;\n"
"border-radius: 8px;\n"
"border-style: none;\n"
"box-sizing: border-box;\n"
"color: #FFFFFF;\n"
"cursor: pointer;\n"
"display: inline-block;\n"
"font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"height: 40px;\n"
"line-height: 20px;\n"
"list-style: none;\n"
"margin: 0;\n"
"outline: none;\n"
"padding: 10px 16px;\n"
"position: relative;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"transition: color 100ms;\n"
"vertical-align: baseline;\n"
"user-select: none;\n"
"-webkit-user-select: none;\n"
"touch-action: manipulation;")
        self.btnRun.setCheckable(False)
        self.btnRun.setObjectName("btnRun")
        self.btnSave = QtWidgets.QPushButton(self.groupbox_io)
        self.btnSave.setEnabled(True)
        self.btnSave.setGeometry(QtCore.QRect(350, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Haas Grot Text R Web,Helvetica Neue,Helvetica,Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(62)
        font.setStrikeOut(False)
        self.btnSave.setFont(font)
        self.btnSave.setStyleSheet("background-color: #EA4C89;\n"
"border-radius: 8px;\n"
"border-style: none;\n"
"box-sizing: border-box;\n"
"color: #FFFFFF;\n"
"cursor: pointer;\n"
"display: inline-block;\n"
"font-family: \"Haas Grot Text R Web\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n"
"font-size: 14px;\n"
"font-weight: 500;\n"
"height: 40px;\n"
"line-height: 20px;\n"
"list-style: none;\n"
"margin: 0;\n"
"outline: none;\n"
"padding: 10px 16px;\n"
"position: relative;\n"
"text-align: center;\n"
"text-decoration: none;\n"
"transition: color 100ms;\n"
"vertical-align: baseline;\n"
"user-select: none;\n"
"-webkit-user-select: none;\n"
"touch-action: manipulation;")
        self.btnSave.setCheckable(False)
        self.btnSave.setObjectName("btnSave")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 240, 801, 651))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lbl_visualize = QtWidgets.QLabel(self.groupBox)
        self.lbl_visualize.setGeometry(QtCore.QRect(10, 10, 451, 631))
        self.lbl_visualize.setAutoFillBackground(False)
        self.lbl_visualize.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;")
        self.lbl_visualize.setText("")
        self.lbl_visualize.setObjectName("lbl_visualize")
        self.tableview_dataframe = QtWidgets.QTableView(self.groupBox)
        self.tableview_dataframe.setGeometry(QtCore.QRect(480, 10, 311, 631))
        self.tableview_dataframe.setObjectName("tableview_dataframe")
        self.lbl_malop = QtWidgets.QLabel(self.centralwidget)
        self.lbl_malop.setGeometry(QtCore.QRect(630, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_malop.setFont(font)
        self.lbl_malop.setObjectName("lbl_malop")
        self.groupBox.raise_()
        self.titleLabel.raise_()
        self.line.raise_()
        self.groupbox_io.raise_()
        self.lbl_malop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hệ thống hỗ trợ nhập điểm tự động"))
        self.titleLabel.setText(_translate("MainWindow", "Hệ thống hỗ trợ nhập điểm thi tự động"))
        self.label.setText(_translate("MainWindow", "Choose a file or folder:"))
        self.btnBrowseInput.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Choose output path:"))
        self.btnBrowseOutput.setText(_translate("MainWindow", "Browse"))
        self.checkbox_file.setText(_translate("MainWindow", "Input as file"))
        self.checkbox_folder.setText(_translate("MainWindow", "Input as folder"))
        self.btnRun.setText(_translate("MainWindow", "Run"))
        self.btnSave.setText(_translate("MainWindow", "Save "))
        self.lbl_malop.setText(_translate("MainWindow", "Mã lớp: "))
